---
# tasks file for update_all_packages

- name: "Update all packages"
  ansible.builtin.package:
    name: "*"
    state: latest
  notify:
    - "Reboot"
    - "Wait for the machine(s) to be ready again"
